services:
  - type: web
    name: ticketbus
    runtime: php
    region: frankfurt1
    buildCommand: "./bin/composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticketbus_db
          property: connectionString
databases:
  - name: ticketbus_db
    databaseName: ticketbus
    user: ticketbus