services:
  - type: web
    name: ticketrbus
    runtime: php
    region: frankfurt1
    buildCommand: "./bin/composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticketrbus-db
          property: connectionString
databases:
  - name: ticketrbus-db
    databaseName: ticketrbus
    user: ticketrbus